<?php
/**
 * Plugin Name: BS LLC — lead forwarder
 * Description: Forwards every Elementor Pro form submission on this site to the BS LLC dashboard (Website Leads), with first-touch ad attribution from a first-party cookie. Configure under Settings → BS LLC lead forwarder.
 * Version: 2026-09-10
 * Author: BS LLC
 *
 * Installable on any WordPress + Elementor Pro site from Plugins → Add New →
 * Upload (zip of this folder). No server access needed: the client slug and
 * webhook key are entered on the settings page. If the site's wp-config.php
 * defines BSLLC_CLIENT_SLUG / BSLLC_WEBFORM_KEY those win over the settings.
 *
 * Source of truth: bsllc-sync-worker/site/elementor/bsllc-lead-forwarder/.
 * Do not edit this file on the server.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

const BSLLC_LF_OPTION       = 'bsllc_lead_forwarder';
const BSLLC_LF_BASE_URL     = 'https://work.bsllc.biz/api/webform/';
const BSLLC_LF_ATTRIB_COOKIE = 'bs_attrib';
const BSLLC_LF_ATTRIB_DAYS  = 90;

function bsllc_lf_settings() {
	$o = get_option( BSLLC_LF_OPTION, array() );
	return array(
		'slug' => defined( 'BSLLC_CLIENT_SLUG' ) ? BSLLC_CLIENT_SLUG : ( isset( $o['slug'] ) ? trim( (string) $o['slug'] ) : '' ),
		'key'  => defined( 'BSLLC_WEBFORM_KEY' ) ? BSLLC_WEBFORM_KEY : ( isset( $o['key'] ) ? trim( (string) $o['key'] ) : '' ),
	);
}

/* ── 0. Settings page ──────────────────────────────────────────────────── */
add_action( 'admin_menu', function () {
	add_options_page( 'BS LLC lead forwarder', 'BS LLC lead forwarder', 'manage_options', 'bsllc-lead-forwarder', function () {
		if ( ! current_user_can( 'manage_options' ) ) { return; }
		if ( isset( $_POST['bsllc_lf_nonce'] ) && wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['bsllc_lf_nonce'] ) ), 'bsllc_lf_save' ) ) {
			update_option( BSLLC_LF_OPTION, array(
				'slug' => sanitize_title( wp_unslash( $_POST['slug'] ?? '' ) ),
				'key'  => sanitize_text_field( wp_unslash( $_POST['key'] ?? '' ) ),
			), false );
			echo '<div class="notice notice-success"><p>Saved.</p></div>';
		}
		$s = bsllc_lf_settings();
		$locked = defined( 'BSLLC_CLIENT_SLUG' ) || defined( 'BSLLC_WEBFORM_KEY' );
		?>
		<div class="wrap">
			<h1>BS LLC lead forwarder</h1>
			<p>Every Elementor Pro form submission on this site is posted to <code><?php echo esc_html( BSLLC_LF_BASE_URL ); ?>&lt;client slug&gt;</code>.</p>
			<?php if ( $locked ) : ?><p><em>Values are defined in wp-config.php and cannot be changed here.</em></p><?php endif; ?>
			<form method="post">
				<?php wp_nonce_field( 'bsllc_lf_save', 'bsllc_lf_nonce' ); ?>
				<table class="form-table">
					<tr><th><label for="slug">Client slug</label></th>
						<td><input name="slug" id="slug" class="regular-text" value="<?php echo esc_attr( $s['slug'] ); ?>" <?php disabled( $locked ); ?>> <span class="description">e.g. <code>franklin-brazing</code></span></td></tr>
					<tr><th><label for="key">Webhook key</label></th>
						<td><input name="key" id="key" type="password" class="regular-text" value="<?php echo esc_attr( $s['key'] ); ?>" <?php disabled( $locked ); ?>></td></tr>
				</table>
				<?php if ( ! $locked ) { submit_button( 'Save' ); } ?>
			</form>
			<p>Status: <?php echo ( '' !== $s['slug'] && '' !== $s['key'] ) ? '<strong style="color:#1a7f37">configured</strong>' : '<strong style="color:#b42318">not configured — submissions are not being forwarded</strong>'; ?></p>
		</div>
		<?php
	} );
} );

/* ── 1. First-touch attribution cookie (every page, in <head>) ─────────── */
add_action( 'wp_head', function () {
	$cookie = BSLLC_LF_ATTRIB_COOKIE;
	$days   = BSLLC_LF_ATTRIB_DAYS;
	?>
<script>
(function(){"use strict";
var COOKIE="<?php echo esc_js( $cookie ); ?>",DAYS=<?php echo (int) $days; ?>,
KEYS=["gclid","gbraid","wbraid","utm_source","utm_medium","utm_campaign","utm_content","utm_term"];
function readCookie(){var m=document.cookie.match(new RegExp("(?:^|; )"+COOKIE+"=([^;]*)"));if(!m)return{};try{return JSON.parse(decodeURIComponent(m[1]))||{}}catch(e){return{}}}
function writeCookie(d){var exp=new Date(Date.now()+DAYS*864e5).toUTCString();document.cookie=COOKIE+"="+encodeURIComponent(JSON.stringify(d))+"; expires="+exp+"; path=/; SameSite=Lax"+(location.protocol==="https:"?"; Secure":"")}
function capture(){var p=new URLSearchParams(location.search),s=readCookie(),c=false;KEYS.forEach(function(k){var v=p.get(k);if(v&&!s[k]){s[k]=v;c=true}});if(c){s.first_seen=s.first_seen||new Date().toISOString();s.landing_page=s.landing_page||location.href;writeCookie(s)}return s}
function fill(form,d){if(!form||form.getAttribute("data-bs-attrib")==="1")return;KEYS.concat(["landing_page"]).forEach(function(k){var v=d[k];if(!v)return;var i=form.querySelector('[name="form_fields['+k+']"]')||form.querySelector('[name="'+k+'"]')||form.querySelector("#form-field-"+k);if(i){if(!i.value)i.value=v}else{var h=document.createElement("input");h.type="hidden";h.name="form_fields["+k+"]";h.value=v;form.appendChild(h)}});form.setAttribute("data-bs-attrib","1")}
function fillAll(){var d=readCookie();if(!Object.keys(d).length)return;document.querySelectorAll("form").forEach(function(f){fill(f,d)})}
capture();
if(document.readyState==="loading"){document.addEventListener("DOMContentLoaded",fillAll)}else{fillAll()}
document.addEventListener("submit",function(e){if(e.target&&e.target.tagName==="FORM")fill(e.target,readCookie())},true);
if(window.jQuery){jQuery(window).on("elementor/frontend/init",function(){if(window.elementorFrontend&&elementorFrontend.hooks){elementorFrontend.hooks.addAction("frontend/element_ready/form.default",function($s){fill($s.find("form")[0],readCookie())})}})}
})();
</script>
	<?php
}, 1 );

/* ── 2. Forward every Elementor Pro submission ─────────────────────────── */
add_action( 'elementor_pro/forms/new_record', function ( $record, $handler ) {
	$s = bsllc_lf_settings();
	if ( '' === $s['slug'] || '' === $s['key'] ) {
		error_log( 'BSLLC webform POST skipped: client slug or webhook key not configured (Settings → BS LLC lead forwarder)' );
		return;
	}

	$raw_fields = (array) $record->get( 'fields' );
	$norm       = array();
	$passthru   = array();
	$fullname   = '';

	foreach ( $raw_fields as $id => $f ) {
		$val = trim( (string) ( isset( $f['value'] ) ? $f['value'] : '' ) );
		if ( '' === $val ) {
			continue;
		}
		$type  = strtolower( isset( $f['type'] ) ? $f['type'] : '' );
		$label = strtolower( isset( $f['title'] ) ? $f['title'] : '' );
		$key   = strtolower( (string) $id );
		$hay   = $key . ' ' . $label;

		$passthru[ 'field_' . $key ] = $val;

		if ( 'email' === $type || false !== strpos( $hay, 'email' ) ) {
			if ( empty( $norm['email'] ) ) { $norm['email'] = $val; }
			continue;
		}
		if ( 'tel' === $type || preg_match( '/phone|tel|mobile|cell/', $hay ) ) {
			if ( empty( $norm['phone'] ) ) { $norm['phone'] = $val; }
			continue;
		}
		if ( preg_match( '/dob|birth/', $hay ) ) {
			if ( empty( $norm['dob'] ) ) { $norm['dob'] = $val; }
			continue;
		}
		if ( preg_match( '/^(gclid|gbraid|wbraid|utm_source|utm_medium|utm_campaign|utm_content|utm_term|landing_page)$/', $key ) ) {
			$norm[ $key ] = $val;
			continue;
		}
		if ( preg_match( '/first/', $hay ) ) {
			if ( empty( $norm['first_name'] ) ) { $norm['first_name'] = $val; }
			continue;
		}
		if ( preg_match( '/last|surname/', $hay ) ) {
			if ( empty( $norm['last_name'] ) ) { $norm['last_name'] = $val; }
			continue;
		}
		if ( preg_match( '/(^|\s)(full |your )?name$/', $label ) || 'name' === $key ) {
			if ( '' === $fullname ) { $fullname = $val; }
		}
	}

	if ( empty( $norm['first_name'] ) && '' !== $fullname ) {
		$parts              = preg_split( '/\s+/', $fullname, 2 );
		$norm['first_name'] = $parts[0];
		if ( ! empty( $parts[1] ) ) {
			$norm['last_name'] = $parts[1];
		}
	}

	if ( ! empty( $_COOKIE[ BSLLC_LF_ATTRIB_COOKIE ] ) ) {
		$cookie = wp_unslash( $_COOKIE[ BSLLC_LF_ATTRIB_COOKIE ] );
		$attrib = json_decode( $cookie, true );
		if ( ! is_array( $attrib ) ) {
			$attrib = json_decode( urldecode( $cookie ), true );
		}
		if ( is_array( $attrib ) ) {
			foreach ( array( 'gclid', 'gbraid', 'wbraid', 'utm_source', 'utm_medium', 'utm_campaign', 'utm_content', 'utm_term', 'landing_page' ) as $k ) {
				if ( empty( $norm[ $k ] ) && ! empty( $attrib[ $k ] ) ) {
					$norm[ $k ] = (string) $attrib[ $k ];
				}
			}
		}
	}

	$norm['form_name'] = (string) $record->get_form_settings( 'form_name' );
	$norm['form_id']   = (string) $record->get_form_settings( 'id' );
	$norm['page_url']  = isset( $_SERVER['HTTP_REFERER'] ) ? esc_url_raw( wp_unslash( $_SERVER['HTTP_REFERER'] ) ) : '';
	$norm['source']    = 'bsllc-lead-forwarder';

	$data = array_merge( $norm, $passthru );

	$res = wp_remote_post(
		BSLLC_LF_BASE_URL . rawurlencode( $s['slug'] ) . '?key=' . rawurlencode( $s['key'] ),
		array(
			'timeout' => 5,
			'headers' => array( 'Content-Type' => 'application/json' ),
			'body'    => wp_json_encode( $data ),
		)
	);

	if ( is_wp_error( $res ) ) {
		error_log( 'BSLLC webform POST failed [' . $norm['form_name'] . ']: ' . $res->get_error_message() );
	} elseif ( wp_remote_retrieve_response_code( $res ) >= 300 ) {
		error_log( 'BSLLC webform POST failed [' . $norm['form_name'] . ']: HTTP ' . wp_remote_retrieve_response_code( $res ) . ' ' . substr( (string) wp_remote_retrieve_body( $res ), 0, 200 ) );
	}
}, 10, 2 );
