<?php
/**
 * Plugin Name: BS LLC — lead forwarder (Ohio Community Health)
 * Description: Forwards EVERY Elementor Pro form submission on this site to the
 *   BS LLC dashboard webhook, with first-touch ad attribution from a first-party
 *   cookie. Replaces the two WPCode snippets "OCH — Elementor form → BS LLC
 *   pipeline" and "OCH — gclid capture" (WPCode 9250). Source of truth:
 *   bsllc-sync-worker/site/och/mu-plugins/bsllc-lead-forwarder.php — deploy
 *   per site/och/README.md. Do not edit this file on the server.
 * Version: 2026-09-03
 *
 * Requires in wp-config.php (never commit the value):
 *   define( 'BSLLC_WEBFORM_KEY', '<the app's WEBFORM_SECRET>' );
 *
 * What it does
 *   1. Prints a small script in <head> on every page that stores gclid + UTMs
 *      from the landing URL in the `bs_attrib` cookie for 90 days (first touch
 *      wins), and copies them into any form at submit time.
 *   2. On elementor_pro/forms/new_record (fires for all 31 forms, whatever
 *      their field IDs), normalises the contact fields by type/label, adds the
 *      cookie's attribution, the form name and the page, and POSTs JSON to the
 *      dashboard. The dashboard's parser (server/webform.ts) reads exactly
 *      these keys.
 *   3. Logs any non-2xx or transport failure to error_log as
 *      "BSLLC webform POST failed [...]" so a broken key or host is visible
 *      in wp-content/debug.log instead of silent.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

const BSLLC_WEBFORM_URL    = 'https://work.bsllc.biz/api/webform/och';
const BSLLC_ATTRIB_COOKIE  = 'bs_attrib';
const BSLLC_ATTRIB_DAYS    = 90;

/* ── 1. First-touch attribution cookie (every page, in <head>) ─────────── */
add_action( 'wp_head', function () {
	$cookie = BSLLC_ATTRIB_COOKIE;
	$days   = BSLLC_ATTRIB_DAYS;
	?>
<script>
(function(){"use strict";
var COOKIE="<?php echo esc_js( $cookie ); ?>",DAYS=<?php echo (int) $days; ?>,
KEYS=["gclid","gbraid","wbraid","utm_source","utm_medium","utm_campaign","utm_content","utm_term"];
function readCookie(){var m=document.cookie.match(new RegExp("(?:^|; )"+COOKIE+"=([^;]*)"));if(!m)return{};try{return JSON.parse(decodeURIComponent(m[1]))||{}}catch(e){return{}}}
function writeCookie(d){var exp=new Date(Date.now()+DAYS*864e5).toUTCString();document.cookie=COOKIE+"="+encodeURIComponent(JSON.stringify(d))+"; expires="+exp+"; path=/; SameSite=Lax"+(location.protocol==="https:"?"; Secure":"")}
function capture(){var p=new URLSearchParams(location.search),s=readCookie(),c=false;KEYS.forEach(function(k){var v=p.get(k);if(v&&!s[k]){s[k]=v;c=true}});if(c){s.first_seen=s.first_seen||new Date().toISOString();s.landing_page=s.landing_page||location.href;writeCookie(s)}return s}
function fill(form,d){if(!form||form.getAttribute("data-bs-attrib")==="1")return;KEYS.concat(["landing_page"]).forEach(function(k){var v=d[k];if(!v)return;var i=form.querySelector('[name="form_fields['+k+']"]')||form.querySelector('[name="'+k+'"]')||form.querySelector("#form-field-"+k);if(i){if(!i.value)i.value=v}else{var h=document.createElement("input");h.type="hidden";h.name="form_fields["+k+"]";h.value=v;form.appendChild(h)}});form.setAttribute("data-bs-attrib","1")}
function fillAll(){var d=readCookie();if(!Object.keys(d).length)return;document.querySelectorAll("form").forEach(function(f){fill(f,d)})}
capture();
if(document.readyState==="loading"){document.addEventListener("DOMContentLoaded",fillAll)}else{fillAll()}
document.addEventListener("submit",function(e){if(e.target&&e.target.tagName==="FORM")fill(e.target,readCookie())},true);
if(window.jQuery){jQuery(window).on("elementor/frontend/init",function(){if(window.elementorFrontend&&elementorFrontend.hooks){elementorFrontend.hooks.addAction("frontend/element_ready/form.default",function($s){fill($s.find("form")[0],readCookie())})}})}
})();
</script>
	<?php
}, 1 );

/* ── 2. Forward every Elementor Pro submission ─────────────────────────── */
add_action( 'elementor_pro/forms/new_record', function ( $record, $handler ) {
	if ( ! defined( 'BSLLC_WEBFORM_KEY' ) || '' === BSLLC_WEBFORM_KEY ) {
		error_log( 'BSLLC webform POST skipped: BSLLC_WEBFORM_KEY is not defined in wp-config.php' );
		return;
	}

	$raw_fields = (array) $record->get( 'fields' );
	$norm       = array();
	$passthru   = array();
	$fullname   = '';

	foreach ( $raw_fields as $id => $f ) {
		$val = trim( (string) ( isset( $f['value'] ) ? $f['value'] : '' ) );
		if ( '' === $val ) {
			continue;
		}
		$type  = strtolower( isset( $f['type'] ) ? $f['type'] : '' );
		$label = strtolower( isset( $f['title'] ) ? $f['title'] : '' );
		$key   = strtolower( (string) $id );
		$hay   = $key . ' ' . $label;

		$passthru[ 'field_' . $key ] = $val;

		if ( 'email' === $type || false !== strpos( $hay, 'email' ) ) {
			if ( empty( $norm['email'] ) ) { $norm['email'] = $val; }
			continue;
		}
		if ( 'tel' === $type || preg_match( '/phone|tel|mobile|cell/', $hay ) ) {
			if ( empty( $norm['phone'] ) ) { $norm['phone'] = $val; }
			continue;
		}
		if ( preg_match( '/dob|birth/', $hay ) ) {
			if ( empty( $norm['dob'] ) ) { $norm['dob'] = $val; }
			continue;
		}
		// Attribution fields the cookie script injected (or the form defines).
		if ( preg_match( '/^(gclid|gbraid|wbraid|utm_source|utm_medium|utm_campaign|utm_content|utm_term|landing_page)$/', $key ) ) {
			$norm[ $key ] = $val;
			continue;
		}
		if ( preg_match( '/first/', $hay ) ) {
			if ( empty( $norm['first_name'] ) ) { $norm['first_name'] = $val; }
			continue;
		}
		if ( preg_match( '/last|surname/', $hay ) ) {
			if ( empty( $norm['last_name'] ) ) { $norm['last_name'] = $val; }
			continue;
		}
		// A single "Name"/"Your name"/"Full name" field — but not "Location name" etc.
		if ( preg_match( '/(^|\s)(full |your )?name$/', $label ) || 'name' === $key ) {
			if ( '' === $fullname ) { $fullname = $val; }
		}
	}

	if ( empty( $norm['first_name'] ) && '' !== $fullname ) {
		$parts              = preg_split( '/\s+/', $fullname, 2 );
		$norm['first_name'] = $parts[0];
		if ( ! empty( $parts[1] ) ) {
			$norm['last_name'] = $parts[1];
		}
	}

	// Attribution from the first-party cookie (first touch). WordPress
	// magic-quotes $_COOKIE, so unslash; the JS URL-encodes the JSON.
	if ( ! empty( $_COOKIE[ BSLLC_ATTRIB_COOKIE ] ) ) {
		$cookie = wp_unslash( $_COOKIE[ BSLLC_ATTRIB_COOKIE ] );
		$attrib = json_decode( $cookie, true );
		if ( ! is_array( $attrib ) ) {
			$attrib = json_decode( urldecode( $cookie ), true );
		}
		if ( is_array( $attrib ) ) {
			foreach ( array( 'gclid', 'gbraid', 'wbraid', 'utm_source', 'utm_medium', 'utm_campaign', 'utm_content', 'utm_term', 'landing_page' ) as $k ) {
				if ( empty( $norm[ $k ] ) && ! empty( $attrib[ $k ] ) ) {
					$norm[ $k ] = (string) $attrib[ $k ];
				}
			}
		}
	}

	$norm['form_name'] = (string) $record->get_form_settings( 'form_name' );
	$norm['form_id']   = (string) $record->get_form_settings( 'id' );
	$norm['page_url']  = isset( $_SERVER['HTTP_REFERER'] ) ? esc_url_raw( wp_unslash( $_SERVER['HTTP_REFERER'] ) ) : '';
	$norm['source']    = 'bsllc-lead-forwarder';

	// Normalised keys first: the dashboard's matcher prefers exact ids and the
	// raw fields are prefixed field_* so they can never shadow these.
	$data = array_merge( $norm, $passthru );

	$res = wp_remote_post(
		BSLLC_WEBFORM_URL . '?key=' . rawurlencode( BSLLC_WEBFORM_KEY ),
		array(
			'timeout' => 5,
			'headers' => array( 'Content-Type' => 'application/json' ),
			'body'    => wp_json_encode( $data ),
		)
	);

	if ( is_wp_error( $res ) ) {
		error_log( 'BSLLC webform POST failed [' . $norm['form_name'] . ']: ' . $res->get_error_message() );
	} elseif ( wp_remote_retrieve_response_code( $res ) >= 300 ) {
		error_log( 'BSLLC webform POST failed [' . $norm['form_name'] . ']: HTTP ' . wp_remote_retrieve_response_code( $res ) . ' ' . substr( (string) wp_remote_retrieve_body( $res ), 0, 200 ) );
	}
}, 10, 2 );
