#!/usr/bin/env tsx
import "dotenv/config";
import pg from "pg";
import { runDashboardSync, type SyncEntry } from "./emit.js";

/**
 * Per-CLIENT HubSpot metrics importer — distinct from import-hubspot.ts,
 * which syncs BS LLC's own internal HubSpot account (our sales pipeline)
 * using the single global HUBSPOT_TOKEN. This reads a CLIENT's own separate
 * HubSpot portal (e.g. Tablespoon's private-events pipeline) and plants
 * hubspot.revenue_cents / hubspot.deals_won / hubspot.leads per month, which
 * the dashboard's revenue-by-channel tile already knows how to read and —
 * when 2+ channels are live in the same period — sum (see
 * shared/schema.ts SIGNAL_CONNECTOR_KEYS.revenue).
 *
 * Auth is a private-app token PER CLIENT, never the client's actual login —
 * generated by the client (or on their behalf) in their own HubSpot account
 * (Settings → Integrations → Private Apps) with crm.objects.deals.read and
 * crm.objects.contacts.read scopes. It is never stored in
 * connector_mappings.external_id (that column is displayed openly in
 * Admin → Connectors and is meant for a non-secret account identifier, e.g.
 * a portal ID) — instead it's kept in the worker-owned
 * client_integration_tokens table, seeded once from a per-client env var
 * named HUBSPOT_TOKEN_<CLIENT_SLUG_UPPER_SNAKE> (e.g. HUBSPOT_TOKEN_TABLESPOON),
 * exactly like integration_tokens seeds the QBO token from an env var on
 * first run.
 *
 * Which clients: any client with an ENABLED connector_mappings row for
 * source='hubspot' (Admin → Connectors → HubSpot, external_id = portal ID,
 * purely a label — not required by the API calls below since the token
 * itself is already portal-scoped).
 *
 *   npm run import-hubspot-metrics -- [--since=2023-01-01] [--dry-run] [--client=<clientId>]
 */

const HS = "https://api.hubapi.com";

function env(n: string): string { const v = process.env[n]; if (!v?.trim()) throw new Error(`Missing ${n}`); return v.trim(); }

interface Args { since: string; dryRun: boolean; onlyClient: string }
function parseArgs(argv: string[]): Args {
  let since = "2023-01-01", dryRun = false, onlyClient = "";
  for (const a of argv) {
    if (a.startsWith("--since=")) since = a.slice("--since=".length);
    else if (a === "--dry-run") dryRun = true;
    else if (a.startsWith("--client=")) onlyClient = a.slice("--client=".length).trim();
  }
  return { since, dryRun, onlyClient };
}

/** "Tablespoon" → "TABLESPOON"; "The OCH Group" → "THE_OCH_GROUP". */
function envSuffix(clientName: string): string {
  return clientName.trim().toUpperCase().replace(/[^A-Z0-9]+/g, "_").replace(/^_+|_+$/g, "");
}

interface HSObj { id: string; properties: Record<string, string | null> }

async function hsGet(token: string, path: string): Promise<any> {
  for (let attempt = 0; ; attempt++) {
    const res = await fetch(`${HS}${path}`, { headers: { Authorization: `Bearer ${token}` } });
    if (res.status === 429 && attempt < 6) { await new Promise((r) => setTimeout(r, 1000 * (attempt + 1))); continue; }
    if (!res.ok) {
      const body = await res.text().catch(() => "");
      const err = new Error(`HubSpot GET ${path} → ${res.status}: ${body.slice(0, 300)}`);
      (err as any).status = res.status;
      throw err;
    }
    return res.json();
  }
}

async function fetchAll(token: string, object: string, properties: string[]): Promise<HSObj[]> {
  const out: HSObj[] = [];
  let after: string | undefined;
  do {
    const qp = new URLSearchParams({ limit: "100" });
    properties.forEach((p) => qp.append("properties", p));
    if (after) qp.set("after", after);
    const data = await hsGet(token, `/crm/v3/objects/${object}?${qp.toString()}`);
    out.push(...((data.results ?? []) as HSObj[]));
    after = data.paging?.next?.after;
  } while (after);
  return out;
}

/**
 * Resolve a client's HubSpot token: prefer whatever's already in
 * client_integration_tokens (the worker's own rotating store); otherwise
 * seed it from the per-client env var and persist it there for next time.
 * Same "seed once, then own it" pattern as integration_tokens for QBO.
 */
async function resolveToken(pgc: pg.Client, clientId: string, clientName: string): Promise<string | null> {
  const { rows } = await pgc.query<{ data: string }>(
    `SELECT data FROM client_integration_tokens WHERE client_id = $1 AND provider = 'hubspot'`, [clientId],
  );
  if (rows[0]) {
    try {
      const parsed = JSON.parse(rows[0].data);
      if (parsed.token && String(parsed.token).trim()) return String(parsed.token).trim();
    } catch { /* fall through to env seed */ }
  }
  const envName = `HUBSPOT_TOKEN_${envSuffix(clientName)}`;
  const fromEnv = process.env[envName]?.trim();
  if (!fromEnv) return null;
  await pgc.query(
    `INSERT INTO client_integration_tokens (client_id, provider, data, updated_at)
     VALUES ($1, 'hubspot', $2, now())
     ON CONFLICT (client_id, provider) DO UPDATE SET data = $2, updated_at = now()`,
    [clientId, JSON.stringify({ token: fromEnv })],
  );
  return fromEnv;
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const databaseUrl = env("DATABASE_URL");
  const dashboardDir = env("DASHBOARD_DIR");
  const sinceYm = args.since.slice(0, 7); // "2023-01"

  const pgc = new pg.Client({ connectionString: databaseUrl });
  await pgc.connect();
  let clients: { id: string; name: string }[];
  try {
    const { rows } = await pgc.query<{ id: string; name: string }>(
      `SELECT c.id, c.name FROM clients c
         JOIN connector_mappings cm ON cm.client_id = c.id AND cm.source = 'hubspot' AND cm.enabled = true
        ORDER BY c.name`,
    );
    clients = args.onlyClient ? rows.filter((r) => r.id === args.onlyClient) : rows;
  } finally {
    // token resolution below needs the same connection; keep it open until then
    await pgc.end();
  }

  if (!clients.length) {
    console.log("No clients have an enabled HubSpot connector — nothing to do.");
    process.exit(0);
  }
  console.log(`HubSpot metrics import — ${clients.length} client(s) with HubSpot enabled, since ${args.since}${args.dryRun ? " (dry-run)" : ""}`);

  const syncs: SyncEntry[] = [];
  const skipped: string[] = [];

  for (const client of clients) {
    const c = new pg.Client({ connectionString: databaseUrl });
    await c.connect();
    let token: string | null;
    try {
      token = await resolveToken(c, client.id, client.name);
    } finally {
      await c.end();
    }
    if (!token) {
      const envName = `HUBSPOT_TOKEN_${envSuffix(client.name)}`;
      console.error(`  ${client.name} — no token on file. Set the ${envName} secret (a private-app token from the client's own HubSpot: Settings → Integrations → Private Apps, scopes crm.objects.deals.read + crm.objects.contacts.read).`);
      skipped.push(client.name);
      continue;
    }

    let deals: HSObj[], contacts: HSObj[];
    try {
      [deals, contacts] = await Promise.all([
        fetchAll(token, "deals", ["amount", "closedate", "hs_is_closed_won"]),
        fetchAll(token, "contacts", ["createdate"]),
      ]);
    } catch (e) {
      const msg = (e instanceof Error ? e.message : String(e)).slice(0, 300);
      console.error(`  ${client.name} — FAILED: ${msg}`);
      skipped.push(client.name);
      continue;
    }

    // Bucket closed-won deal revenue + count, and new-contact count, by month.
    const byMonth = new Map<string, { revenueCents: number; dealsWon: number; leads: number }>();
    const bump = (ym: string) => {
      let e = byMonth.get(ym);
      if (!e) { e = { revenueCents: 0, dealsWon: 0, leads: 0 }; byMonth.set(ym, e); }
      return e;
    };
    for (const d of deals) {
      if (d.properties.hs_is_closed_won !== "true") continue;
      const closeDate = d.properties.closedate;
      if (!closeDate) continue;
      const ym = closeDate.slice(0, 7);
      if (ym < sinceYm) continue;
      const amount = Number(d.properties.amount ?? 0);
      const e = bump(ym);
      e.revenueCents += Number.isFinite(amount) ? Math.round(amount * 100) : 0;
      e.dealsWon += 1;
    }
    for (const ct of contacts) {
      const created = ct.properties.createdate;
      if (!created) continue;
      const ym = String(created).slice(0, 7);
      if (ym < sinceYm) continue;
      bump(ym).leads += 1;
    }

    let planted = 0;
    for (const [ym, v] of Array.from(byMonth.entries()).sort()) {
      const y = Number(ym.slice(0, 4)), m = Number(ym.slice(5, 7));
      const last = new Date(Date.UTC(y, m, 0)).getUTCDate();
      const start = `${ym}-01`, end = `${ym}-${String(last).padStart(2, "0")}`;
      syncs.push({
        client_id: client.id,
        source: "hubspot",
        period_start: start,
        period_end: end,
        synced_at: `${end}T12:00:00.000Z`,
        data_state: "live",
        error_message: null,
        metrics: {
          "hubspot.revenue_cents": v.revenueCents,
          "hubspot.deals_won": v.dealsWon,
          "hubspot.leads": v.leads,
        },
      });
      planted++;
    }
    console.log(`  ${client.name} — ${deals.length} deals, ${contacts.length} contacts → ${planted} months planted`);
  }

  if (!syncs.length) {
    if (skipped.length) { console.error(`\nEvery client was skipped — nothing imported.`); process.exit(1); }
    console.log("No HubSpot data in range for any client — nothing to plant.");
    process.exit(0);
  }
  console.log(`\nPlanting ${syncs.length} monthly snapshot(s) from ${clients.length - skipped.length} client(s).`);
  const code = runDashboardSync({ databaseUrl, dashboardDir }, syncs, { dryRun: args.dryRun });
  if (skipped.length) console.error(`\n${skipped.length} client(s) skipped (see above): ${skipped.join(", ")}`);
  process.exit(code || (skipped.length ? 1 : 0));
}

main().catch((e) => { console.error(e instanceof Error ? e.message : e); process.exit(1); });
