#!/usr/bin/env tsx
import "dotenv/config";
import pg from "pg";
import { runDashboardSync, type SyncEntry } from "./emit.js";
import { fetchHubspotDealsWithContacts, hsFetchAll, hubspotBucket, hubspotDealSource, hubspotDealStage, isAttributed, loadWebInquiryIndex, matchWebInquiry, looksLikeSample, resolveHubspotToken, type Bucket, type HSObj } from "./attribution.js";

/**
 * Per-CLIENT HubSpot metrics importer — distinct from import-hubspot.ts,
 * which syncs BS LLC's own internal HubSpot account (our sales pipeline)
 * using the single global HUBSPOT_TOKEN. This reads a CLIENT's own separate
 * HubSpot portal (e.g. Tablespoon's private-events pipeline) and plants
 * hubspot.revenue_cents / hubspot.deals_won / hubspot.leads per month, which
 * are company-wide totals (context only on a case study), PLUS the
 * case-study keys hubspot.cw_revenue_bsllc_cents / hubspot.cw_deals_bsllc:
 * won deals whose original source is a channel we run (paid / organic
 * search) or whose contact matches a web inquiry we captured where HubSpot
 * has no source — the same rule match-web-leads-to-crm applies row by row
 * (src/attribution.ts), so the monthly figure and the drill-down agree.
 * the dashboard's revenue-by-channel tile already knows how to read and —
 * when 2+ channels are live in the same period — sum (see
 * shared/schema.ts SIGNAL_CONNECTOR_KEYS.revenue).
 *
 * Auth is a private-app token PER CLIENT, never the client's actual login —
 * generated by the client (or on their behalf) in their own HubSpot account
 * (Settings → Integrations → Private Apps) with crm.objects.deals.read and
 * crm.objects.contacts.read scopes. It is never stored in
 * connector_mappings.external_id (that column is displayed openly in
 * Admin → Connectors and is meant for a non-secret account identifier, e.g.
 * a portal ID) — instead it's kept in the worker-owned
 * client_integration_tokens table, seeded once from a per-client env var
 * named HUBSPOT_TOKEN_<CLIENT_SLUG_UPPER_SNAKE> (e.g. HUBSPOT_TOKEN_TABLESPOON),
 * exactly like integration_tokens seeds the QBO token from an env var on
 * first run.
 *
 * Which clients: any client with an ENABLED connector_mappings row for
 * source='hubspot' (Admin → Connectors → HubSpot, external_id = portal ID,
 * purely a label — not required by the API calls below since the token
 * itself is already portal-scoped).
 *
 *   npm run import-hubspot-metrics -- [--since=2023-01-01] [--dry-run] [--client=<clientId>]
 */

const HS = "https://api.hubapi.com";

function env(n: string): string { const v = process.env[n]; if (!v?.trim()) throw new Error(`Missing ${n}`); return v.trim(); }

interface Args { since: string; dryRun: boolean; onlyClient: string }
function parseArgs(argv: string[]): Args {
  let since = "2023-01-01", dryRun = false, onlyClient = "";
  for (const a of argv) {
    if (a.startsWith("--since=")) since = a.slice("--since=".length);
    else if (a === "--dry-run") dryRun = true;
    else if (a.startsWith("--client=")) onlyClient = a.slice("--client=".length).trim();
  }
  return { since, dryRun, onlyClient };
}

/** "Tablespoon" → "TABLESPOON"; "The OCH Group" → "THE_OCH_GROUP". */
function envSuffix(clientName: string): string {
  return clientName.trim().toUpperCase().replace(/[^A-Z0-9]+/g, "_").replace(/^_+|_+$/g, "");
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const databaseUrl = env("DATABASE_URL");
  const dashboardDir = env("DASHBOARD_DIR");
  const sinceYm = args.since.slice(0, 7); // "2023-01"

  const pgc = new pg.Client({ connectionString: databaseUrl });
  await pgc.connect();
  let clients: { id: string; name: string }[];
  try {
    const { rows } = await pgc.query<{ id: string; name: string }>(
      `SELECT c.id, c.name FROM clients c
         JOIN connector_mappings cm ON cm.client_id = c.id AND cm.source = 'hubspot' AND cm.enabled = true
        ORDER BY c.name`,
    );
    clients = args.onlyClient ? rows.filter((r) => r.id === args.onlyClient) : rows;
  } finally {
    // token resolution below needs the same connection; keep it open until then
    await pgc.end();
  }

  if (!clients.length) {
    console.log("No clients have an enabled HubSpot connector — nothing to do.");
    process.exit(0);
  }
  console.log(`HubSpot metrics import — ${clients.length} client(s) with HubSpot enabled, since ${args.since}${args.dryRun ? " (dry-run)" : ""}`);

  const syncs: SyncEntry[] = [];
  const skipped: string[] = [];

  for (const client of clients) {
    const c = new pg.Client({ connectionString: databaseUrl });
    await c.connect();
    let token: string | null;
    let webIdx: Awaited<ReturnType<typeof loadWebInquiryIndex>>;
    try {
      token = await resolveHubspotToken(c, client.id, client.name);
      webIdx = await loadWebInquiryIndex(c, client.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, ""), null);
    } finally {
      await c.end();
    }
    if (!token) {
      const envName = `HUBSPOT_TOKEN_${envSuffix(client.name)}`;
      console.error(`  ${client.name} — no token on file. Set the ${envName} secret (a private-app token from the client's own HubSpot: Settings → Integrations → Private Apps, scopes crm.objects.deals.read + crm.objects.contacts.read).`);
      skipped.push(client.name);
      continue;
    }

    let deals: HSObj[], contacts: HSObj[], contactsById: Map<string, HSObj>;
    try {
      [{ deals, contactsById }, contacts] = await Promise.all([
        fetchHubspotDealsWithContacts(token),
        hsFetchAll(token, "contacts", ["createdate"]),
      ]);
    } catch (e) {
      const msg = (e instanceof Error ? e.message : String(e)).slice(0, 300);
      console.error(`  ${client.name} — FAILED: ${msg}`);
      skipped.push(client.name);
      continue;
    }

    // Bucket closed-won deal revenue + count, and new-contact count, by month.
    type Month = { revenueCents: number; dealsWon: number; leads: number; cw: Record<Bucket, number>; cwDealsBsllc: number };
    const byMonth = new Map<string, Month>();
    const bump = (ym: string) => {
      let e = byMonth.get(ym);
      if (!e) { e = { revenueCents: 0, dealsWon: 0, leads: 0, cw: { bsllc: 0, other: 0, manual: 0, unknown: 0 }, cwDealsBsllc: 0 }; byMonth.set(ym, e); }
      return e;
    };
    const tally: Record<Bucket, number> = { bsllc: 0, other: 0, manual: 0, unknown: 0 };
    let matchedAsSource = 0, samples = 0;
    for (const d of deals) {
      if (hubspotDealStage(d) !== "won") continue;
      const closeDate = d.properties.closedate;
      if (!closeDate) continue;
      const ym = closeDate.slice(0, 7);
      if (ym < sinceYm) continue;
      const amount = Number(d.properties.amount ?? 0);
      const cents = Number.isFinite(amount) ? Math.round(amount * 100) : 0;
      const e = bump(ym);
      e.revenueCents += cents;
      e.dealsWon += 1;
      // Case-study slice: the CRM's own original source, else a match to a
      // web inquiry we captured (see attribution.ts — one rule for both jobs).
      const { value: source, contact } = hubspotDealSource(d, contactsById);
      const bucket = hubspotBucket(source);
      const matched = !!matchWebInquiry(webIdx, { emails: [contact?.properties.email], phones: [contact?.properties.phone, contact?.properties.mobilephone], gclid: contact?.properties.hs_google_click_id });
      const sample = looksLikeSample(d.properties.dealname, contact?.properties.email);
      if (sample) { samples++; continue; }
      const ours = isAttributed(bucket, matched, sample);
      if (ours && bucket !== "bsllc") matchedAsSource++;
      const slot: Bucket = ours ? "bsllc" : bucket;
      e.cw[slot] += cents;
      if (ours) e.cwDealsBsllc += 1;
      tally[slot] += 1;
    }
    console.log(`  ${client.name} — won deals by source: ${tally.bsllc} ours (${matchedAsSource} via web-lead match) · ${tally.other} other · ${tally.manual} offline · ${tally.unknown} no source${samples ? ` · ${samples} sample skipped` : ""}`);
    for (const ct of contacts) {
      const created = ct.properties.createdate;
      if (!created) continue;
      const ym = String(created).slice(0, 7);
      if (ym < sinceYm) continue;
      bump(ym).leads += 1;
    }

    let planted = 0;
    for (const [ym, v] of Array.from(byMonth.entries()).sort()) {
      const y = Number(ym.slice(0, 4)), m = Number(ym.slice(5, 7));
      const last = new Date(Date.UTC(y, m, 0)).getUTCDate();
      const start = `${ym}-01`, end = `${ym}-${String(last).padStart(2, "0")}`;
      syncs.push({
        client_id: client.id,
        source: "hubspot",
        period_start: start,
        period_end: end,
        synced_at: `${end}T12:00:00.000Z`,
        data_state: "live",
        error_message: null,
        metrics: {
          "hubspot.revenue_cents": v.revenueCents,
          "hubspot.deals_won": v.dealsWon,
          "hubspot.leads": v.leads,
          "hubspot.cw_revenue_bsllc_cents": v.cw.bsllc,
          "hubspot.cw_deals_bsllc": v.cwDealsBsllc,
          "hubspot.cw_revenue_other_cents": v.cw.other,
          "hubspot.cw_revenue_manual_cents": v.cw.manual,
          "hubspot.cw_revenue_unknown_cents": v.cw.unknown,
        },
      });
      planted++;
    }
    console.log(`  ${client.name} — ${deals.length} deals, ${contacts.length} contacts → ${planted} months planted`);
  }

  if (!syncs.length) {
    if (skipped.length) { console.error(`\nEvery client was skipped — nothing imported.`); process.exit(1); }
    console.log("No HubSpot data in range for any client — nothing to plant.");
    process.exit(0);
  }
  console.log(`\nPlanting ${syncs.length} monthly snapshot(s) from ${clients.length - skipped.length} client(s).`);
  const code = runDashboardSync({ databaseUrl, dashboardDir }, syncs, { dryRun: args.dryRun });
  if (skipped.length) console.error(`\n${skipped.length} client(s) skipped (see above): ${skipped.join(", ")}`);
  process.exit(code || (skipped.length ? 1 : 0));
}

main().catch((e) => { console.error(e instanceof Error ? e.message : e); process.exit(1); });
